"""The numerical-product contract for the Evaluation and Experiment stages.

Every product of either stage carries, for each observation, the three point estimates defined in
:data:`evaluation.POINT_ESTIMATES` -- ``map_estimate``, ``posterior_quantiles`` (the marginal
median is the quantile at level 0.50) and ``posterior_sgm`` -- plus a JSON manifest recording the
computation contract under which they were made. This module is the single place that says what a
valid product looks like, validates one (refusing it with the observation, estimate and stage
named: before any analysis when a product is read, and fail-closed at publication when one is
written -- the computation has finished by then, and what is refused is the product), rejects
the obsolete pre-0.1.16 schema, and checks that shards belong to one computation before they are
merged.

What "validated" means here, in full:

* no obsolete field; a manifest present, of this schema version and of the requested stage;
* every contract entry present, of the declared type and value range (versions supported, pool
  mode known, draw label matching the pool mode, SGM scale finite and positive with one entry per
  parameter, quantile levels canonical, optimizer / code / checkpoint / run-identity / seed-policy
  blocks complete, window geometry present for the experiment stage and absent for evaluation,
  condition labels equal to the stored ``kinds``);
* a run identity that is exactly the logical invocation (product label and the launcher-created
  invocation id), compared across shards, and a separate execution block naming the attempt that
  wrote the product (its Slurm job id, or null), recorded but never compared -- a missing rank
  recomputed in a new job, or locally, is the same invocation executed again;
* a code block whose startup and at-write implementation records (aggregate hash and per-file
  entries) are identical -- compared directly, not read from the flag -- with a
  ``changed_during_run`` flag that agrees;
* exactly the optional arrays the manifest declares in ``stored_optional_fields``: optional
  storage is a run-level setting, part of the contract every shard shares;
* every required array present with the declared shape; every estimate, score and truth finite;
  quantiles nondecreasing along the level axis (equal neighbors allowed); identifier arrays
  integer-valued; the optional posterior cloud of shape ``(N, n_summary_draws, D)`` and finite;
* observation identifiers unique (and equal to an expected inventory when one is given);
* for a merged product, one ``shards`` record per input shard (rank, world size, observation
  count, write time, execution attempt) whose observation counts sum to the product's.

Schema versions are distinct from the package version and from the marker that identifies the
MAP bookkeeping correction (0.1.15): a package release may change neither, and a schema change may
carry no numerical change.
"""
from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone

import numpy as np

#: Schema 1 is frozen as released with 0.1.16. It was refined in place during that release while no
#: product of it existed on disk. Any later incompatible change -- a new required key or array, or
#: a rule that refuses a product schema 1 accepts -- takes a new version number; a product of the
#: older version is then refused explicitly, or migrated by an explicit action that records its
#: source, and is never reinterpreted in place.
ARTIFACT_SCHEMA_VERSION = 1
#: Estimate-definition versions (``evaluation.ESTIMATE_DEFINITIONS_VERSION``) this schema reads.
SUPPORTED_ESTIMATE_DEFINITIONS_VERSIONS = (1,)
MANIFEST_KEY = "manifest_json"          # stored as a 0-d unicode array inside the .npz
#: The quantile levels every product stores along the last axis of ``posterior_quantiles``, in this
#: order. They are recorded in the manifest AND validated against this tuple, so a reader that
#: locates the median by level (``median_level_index``) and one that reads the 50 % / 90 %
#: intervals as levels (1, 3) / (0, 4) are both grounded in the same validated fact.
CANONICAL_QUANTILE_LEVELS = (0.05, 0.25, 0.50, 0.75, 0.95)
#: What the summary draws are under each candidate-pool mode. ``evaluation.draw_label`` reads
#: this table; the validator requires a product's ``draw_label`` to be the entry for its
#: ``pool_mode``, so the two can never disagree inside one manifest.
DRAW_LABELS = {"bounded": "posterior-draw", "unrestricted": "flow-draw"}
#: The environment variable through which a launcher hands every rank of one sharded invocation
#: the same identifier. Generated by the launcher BEFORE the ranks start; a rank generating its
#: own would make its shard unmergeable with the others.
INVOCATION_ID_ENV = "SRM_AND_SBI_INVOCATION_ID"

# Fields the pre-0.1.16 schema used, with the reason each is refused. A product carrying one of
# these is an OLD product; renaming a field is never a numerical correction, so nothing here falls
# back to reading it.
OBSOLETE_FIELDS = {
    "inferred_log10": "renamed to map_estimate in artifact schema 1 (0.1.16)",
}

# Required arrays per stage and their shape rule: ("N", "D") means (n_observations, n_parameters);
# ("N", "D", "Q") adds the quantile-level axis; ("N",) is one value per observation.
_ESTIMATE_FIELDS = {
    "map_estimate": ("N", "D"),
    "posterior_quantiles": ("N", "D", "Q"),
    "posterior_sgm": ("N", "D"),
}
STAGE_FIELDS = {
    "evaluation": {**_ESTIMATE_FIELDS, "true_log10": ("N", "D"), "scores": ("N",),
                   "task_index": ("N",), "sim_index": ("N",)},
    "experiment": {**_ESTIMATE_FIELDS, "scores": ("N",), "kind_index": ("N",), "cell": ("N",),
                   "chunk": ("N",)},
}
# Per-observation float arrays that must be finite everywhere (the estimates, the score, the truth).
_FINITE_FIELDS = {
    "evaluation": ("map_estimate", "posterior_quantiles", "posterior_sgm", "scores", "true_log10"),
    "experiment": ("map_estimate", "posterior_quantiles", "posterior_sgm", "scores"),
}
# Per-run (not per-observation) arrays a stage stores beside the observation arrays.
STAGE_RUN_FIELDS = {"evaluation": (), "experiment": ("kinds",)}
# Optional per-observation arrays and their shape rule ("S" = n_summary_draws).
OPTIONAL_FIELDS = {"experiment": {"posterior_samples_cloud": ("N", "S", "D")}, "evaluation": {}}
# The observation identifier of each stage: the fields whose tuple must be unique per row and
# must equal the expected inventory when a merge knows it.
OBSERVATION_ID_FIELDS = {
    "evaluation": ("task_index", "sim_index"),
    "experiment": ("kind_index", "cell", "chunk"),
}
# Manifest entries that must agree across shards of one computation. Observation-, rank- and
# attempt-specific entries (n_observations, rank, world_size, execution, written_at) are
# deliberately not here: a replacement rank recomputed in another Slurm job differs in exactly
# those, and must still merge.
CONTRACT_KEYS = (
    "artifact_schema_version", "estimate_definitions_version", "stage", "parameter_keys",
    "coordinate_transform", "pool_mode", "draw_label", "n_summary_draws", "quantile_levels",
    "sgm_scale", "sgm_coordinates", "optimizer", "code", "checkpoint_sha256", "run_identity",
    "seed_policy", "window_geometry", "condition_labels", "stored_optional_fields",
)
# Every key a manifest must carry (the contract plus the per-product bookkeeping).
REQUIRED_MANIFEST_KEYS = CONTRACT_KEYS + (
    "execution", "observation_id_fields", "n_observations", "rank", "world_size", "written_at")
# Keys of the execution block (the attempt that wrote a product) and of one ``shards`` record in
# a merged manifest.
EXECUTION_KEYS = ("job_id",)
SHARD_RECORD_KEYS = ("rank", "world_size", "n_observations", "written_at", "execution")
# Keys the optimizer block (``evaluation.optimizer_contract``) must carry.
OPTIMIZER_KEYS = ("pool_mode", "theta_prex_size", "elite_prex_size", "numb_steps",
                  "optimizer_patience", "scheduler_patience", "learning_rate",
                  "learning_rate_minimum", "learning_rate_factor", "tolerance", "bookkeeping")
_SHA256_LEN = 64


class SchemaError(ValueError):
    """A product does not satisfy the contract. The message names what and where."""


# ---- manifest -----------------------------------------------------------------------------------

def build_manifest(*, stage, parameter_keys, coordinate_transform, pool_mode, n_summary_draws,
                   quantile_levels, sgm_scale, sgm_coordinates, optimizer, code,
                   checkpoint_sha256, run_identity, execution, seed_policy, window_geometry,
                   condition_labels, stored_optional_fields, n_observations, rank=None,
                   world_size=None, estimate_definitions_version, draw_label) -> dict:
    """Assemble the computation contract a product stores. Every argument is required by name so
    a caller cannot forget one.

    ``optimizer`` is :func:`evaluation.optimizer_contract`; ``code`` is
    :func:`provenance.finalize_code_provenance` (startup and at-write implementation hashes);
    ``checkpoint_sha256`` is the weights checksum of the estimator ACTUALLY LOADED (read from the
    loaded artifact at startup, never from the path again later); ``run_identity`` is
    :func:`run_identity` (the logical invocation, compared across shards) and ``execution`` is
    :func:`execution_identity` (the attempt that writes this product, recorded but never
    compared); ``seed_policy`` is :func:`seed_policy`; ``window_geometry`` is
    :func:`window_geometry` for the experiment stage and ``None`` for evaluation;
    ``condition_labels`` is the experiment stage's ``kinds`` list and ``None`` for evaluation;
    ``stored_optional_fields`` lists the optional arrays (:data:`OPTIONAL_FIELDS`) this RUN
    stores -- every product of the run carries exactly these; ``draw_label`` says what the draws
    are (:data:`DRAW_LABELS`)."""
    if stage not in STAGE_FIELDS:
        raise SchemaError(f"unknown stage {stage!r}; expected one of {sorted(STAGE_FIELDS)}")
    return {
        "artifact_schema_version": ARTIFACT_SCHEMA_VERSION,
        "estimate_definitions_version": int(estimate_definitions_version),
        "stage": stage,
        "parameter_keys": [str(k) for k in parameter_keys],
        "coordinate_transform": str(coordinate_transform),
        "pool_mode": str(pool_mode),
        "draw_label": str(draw_label),
        "n_summary_draws": int(n_summary_draws),
        "quantile_levels": [float(q) for q in quantile_levels],
        "sgm_scale": [float(s) for s in np.asarray(sgm_scale, dtype=float).ravel()],
        "sgm_coordinates": str(sgm_coordinates),
        "optimizer": dict(optimizer),
        "code": dict(code),
        "checkpoint_sha256": (None if checkpoint_sha256 is None else str(checkpoint_sha256)),
        "run_identity": dict(run_identity),
        "execution": dict(execution),
        "seed_policy": dict(seed_policy),
        "window_geometry": (None if window_geometry is None else dict(window_geometry)),
        "condition_labels": (None if condition_labels is None
                             else [str(k) for k in condition_labels]),
        "stored_optional_fields": [str(k) for k in stored_optional_fields],
        "observation_id_fields": list(OBSERVATION_ID_FIELDS[stage]),
        "n_observations": int(n_observations),
        "rank": rank, "world_size": world_size,
        "written_at": _now(),
    }


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def run_identity(product_label: str, *, distributed: bool) -> dict:
    """The LOGICAL identity of one computation, shared by every shard of it and compared when
    shards are merged: the product it writes and the invocation it belongs to.

    The invocation identifier comes from :data:`INVOCATION_ID_ENV`, which the launcher sets ONCE
    before the ranks start, so every shard of one invocation carries the same value, while a
    fresh launch of the stage (even inside the same Slurm job) creates a new one and its shards
    cannot mix with a stale earlier set. Recomputing a missing rank of an existing invocation
    passes that invocation's identifier explicitly: it is the same invocation executed again.
    Which Slurm job ran a given rank is deliberately NOT part of this identity; it is the
    execution attempt (:func:`execution_identity`), recorded per product and never compared, so a
    replacement rank run in a new job, or locally, merges with the original shards. A
    distributed rank without the identifier stops here rather than inventing one no other rank
    shares; a single-process run generates its own."""
    invocation = os.environ.get(INVOCATION_ID_ENV)
    if not invocation:
        if distributed:
            raise SchemaError(
                f"{INVOCATION_ID_ENV} is not set: a sharded run needs one invocation identifier "
                f"created by the launcher before the ranks start (the stage scripts export it); "
                f"a rank generating its own would make its shard unmergeable.")
        invocation = str(uuid.uuid4())
    return {"product_label": str(product_label), "invocation_id": str(invocation)}


def execution_identity() -> dict:
    """The execution ATTEMPT that writes a product: the Slurm job it ran under (``None`` outside
    Slurm). Recorded in every product, retained per shard in a merged manifest, and never
    compared across shards -- a replacement rank records its own job, never the original's."""
    return {"job_id": os.environ.get("SLURM_JOB_ID") or None}


def _valid_execution(block) -> bool:
    return (isinstance(block, dict) and set(block) == set(EXECUTION_KEYS)
            and (block["job_id"] is None
                 or (isinstance(block["job_id"], str) and bool(block["job_id"]))))


def seed_policy(base_seed) -> dict:
    """How the run was seeded: the base seed (``None`` = nondeterministic) and how each rank
    derives its own generator state from it. The stages seed torch / numpy / random with the
    SAME base seed on every rank and apply no rank offset; the policy records that explicitly so
    a reader knows two ranks' draws are not independent streams under a fixed seed."""
    return {"base_seed": (None if base_seed is None else int(base_seed)),
            "per_rank": "same base seed on every rank; no rank offset"}


def window_geometry(*, n_frames: int, step_frames: int, span_frames) -> dict:
    """The experiment stage's windowing: model-window length, stride and nominal recording
    length, all in frames. Two shards whose ``(cell, chunk)`` identifiers agree but whose
    geometry differs describe different frame ranges and are not merged."""
    return {"n_frames": int(n_frames), "step_frames": int(step_frames),
            "span_frames": (None if span_frames is None else int(span_frames))}


def encode_manifest(manifest: dict) -> np.ndarray:
    """The manifest as the 0-d unicode array ``np.savez`` stores under :data:`MANIFEST_KEY`."""
    return np.asarray(json.dumps(manifest, sort_keys=True, default=_json_default))


def decode_manifest(value) -> dict:
    return json.loads(str(np.asarray(value).item()))


def _json_default(o):
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, np.ndarray):
        return o.tolist()
    raise TypeError(f"manifest value of type {type(o).__name__} is not JSON-serializable")


def empty_product_arrays(stage: str, *, n_parameters: int, n_levels: int = None,
                         run_fields: dict = None) -> dict:
    """Correctly shaped zero-observation arrays for a stage: ``(0, D)``, ``(0, D, Q)`` and
    ``(0,)`` as the shape rules require -- NOT the ``(0,)`` that converting an empty list gives
    every array. ``run_fields`` (e.g. ``{"kinds": ...}``) are copied in. Used by a rank that drew
    no work, so it still writes a valid, mergeable shard."""
    q = len(CANONICAL_QUANTILE_LEVELS) if n_levels is None else int(n_levels)
    dims = {"N": 0, "D": int(n_parameters), "Q": q}
    out = {}
    for key, rule in STAGE_FIELDS[stage].items():
        dtype = np.int64 if key in OBSERVATION_ID_FIELDS[stage] else float
        out[key] = np.empty(tuple(dims[r] for r in rule), dtype=dtype)
    for key, value in (run_fields or {}).items():
        out[key] = np.asarray(value)
    return out


# ---- validation ---------------------------------------------------------------------------------

def reject_obsolete(arrays, *, source="product") -> None:
    """Refuse a product that carries any pre-0.1.16 field. Conversion, when warranted, is an
    explicit action that writes a NEW product and records its source; it never happens here."""
    present = [k for k in OBSOLETE_FIELDS if k in arrays]
    if present:
        reasons = "; ".join(f"{k}: {OBSOLETE_FIELDS[k]}" for k in present)
        raise SchemaError(
            f"Obsolete artifact schema in {source}: {', '.join(present)} is no longer supported "
            f"({reasons}). Use a regenerated or explicitly migrated product. Schema conversion "
            f"does not repair affected MAP estimates.")


def _is_sha256(value) -> bool:
    return (isinstance(value, str) and len(value) == _SHA256_LEN
            and all(c in "0123456789abcdef" for c in value))


def _require(cond, source, message):
    if not cond:
        raise SchemaError(f"{source}: {message}")


def validate_manifest(manifest: dict, *, stage: str, source="product") -> dict:
    """Validate the manifest alone: every required key present, of the declared type and within
    the supported values, with the cross-field rules (draw label matches pool mode, SGM scale has
    one positive finite entry per parameter, window geometry / condition labels present exactly
    for the experiment stage, implementation unchanged during the run). Returns the manifest."""
    _require(isinstance(manifest, dict), source, "manifest is not a JSON object.")
    missing = [k for k in REQUIRED_MANIFEST_KEYS if k not in manifest]
    _require(not missing, source, f"manifest lacks required key(s) {missing}.")
    _require(manifest["artifact_schema_version"] == ARTIFACT_SCHEMA_VERSION, source,
             f"artifact_schema_version {manifest['artifact_schema_version']!r} != "
             f"{ARTIFACT_SCHEMA_VERSION}.")
    _require(manifest["estimate_definitions_version"] in SUPPORTED_ESTIMATE_DEFINITIONS_VERSIONS,
             source, f"estimate_definitions_version {manifest['estimate_definitions_version']!r} "
                     f"is not supported {list(SUPPORTED_ESTIMATE_DEFINITIONS_VERSIONS)}.")
    _require(manifest["stage"] == stage, source, f"manifest stage {manifest['stage']!r} != {stage!r}.")
    keys = manifest["parameter_keys"]
    _require(isinstance(keys, list) and keys and all(isinstance(k, str) for k in keys)
             and len(set(keys)) == len(keys), source,
             "parameter_keys must be a non-empty list of distinct strings.")
    d = len(keys)
    _require(isinstance(manifest["coordinate_transform"], str) and manifest["coordinate_transform"],
             source, "coordinate_transform must be a non-empty string.")
    pool_mode = manifest["pool_mode"]
    _require(pool_mode in DRAW_LABELS, source,
             f"pool_mode {pool_mode!r} is not one of {sorted(DRAW_LABELS)}.")
    _require(manifest["draw_label"] == DRAW_LABELS[pool_mode], source,
             f"draw_label {manifest['draw_label']!r} does not match pool_mode {pool_mode!r} "
             f"(expected {DRAW_LABELS[pool_mode]!r}).")
    n_draws = manifest["n_summary_draws"]
    _require(isinstance(n_draws, int) and not isinstance(n_draws, bool) and n_draws > 0, source,
             f"n_summary_draws {n_draws!r} must be a positive integer.")
    levels = manifest["quantile_levels"]
    _require(isinstance(levels, list) and all(isinstance(v, (int, float)) for v in levels), source,
             "quantile_levels must be a list of numbers.")
    _require(tuple(round(float(v), 12) for v in levels) == CANONICAL_QUANTILE_LEVELS, source,
             f"quantile_levels {levels} differ from the canonical {list(CANONICAL_QUANTILE_LEVELS)}; "
             f"the marginal median and the 50 % / 90 % intervals cannot be located.")
    scale = manifest["sgm_scale"]
    _require(isinstance(scale, list) and len(scale) == d, source,
             f"sgm_scale has {len(scale) if isinstance(scale, list) else 'no'} entries; "
             f"expected one per parameter ({d}).")
    scale_arr = np.asarray(scale, dtype=float) if all(isinstance(s, (int, float)) for s in scale) \
        else np.array([np.nan])
    _require(bool(np.all(np.isfinite(scale_arr)) and np.all(scale_arr > 0)), source,
             f"sgm_scale entries must be finite and positive; got {scale}.")
    _require(isinstance(manifest["sgm_coordinates"], str) and manifest["sgm_coordinates"], source,
             "sgm_coordinates must be a non-empty string.")
    opt = manifest["optimizer"]
    _require(isinstance(opt, dict), source, "optimizer must be an object.")
    opt_missing = [k for k in OPTIMIZER_KEYS if k not in opt]
    _require(not opt_missing, source, f"optimizer block lacks {opt_missing}.")
    _require(opt["pool_mode"] == pool_mode, source,
             f"optimizer.pool_mode {opt['pool_mode']!r} != manifest pool_mode {pool_mode!r}.")
    for k in ("theta_prex_size", "elite_prex_size", "numb_steps", "optimizer_patience",
              "scheduler_patience"):
        _require(isinstance(opt[k], int) and not isinstance(opt[k], bool) and opt[k] > 0, source,
                 f"optimizer.{k} {opt[k]!r} must be a positive integer.")
    for k in ("learning_rate", "learning_rate_minimum", "learning_rate_factor", "tolerance"):
        _require(isinstance(opt[k], (int, float)) and np.isfinite(opt[k]) and opt[k] > 0, source,
                 f"optimizer.{k} {opt[k]!r} must be finite and positive.")
    _require(isinstance(opt["bookkeeping"], str) and opt["bookkeeping"], source,
             "optimizer.bookkeeping must name the bookkeeping rule.")
    code = manifest["code"]
    _require(isinstance(code, dict), source, "code must be an object.")
    for k in ("git_head", "git_dirty", "implementation", "implementation_at_write",
              "changed_during_run"):
        _require(k in code, source, f"code block lacks {k!r}.")
    _require(code["git_head"] is None or isinstance(code["git_head"], str), source,
             "code.git_head must be a string or null.")
    _require(code["git_dirty"] is None or isinstance(code["git_dirty"], bool), source,
             "code.git_dirty must be a boolean or null.")
    for k in ("implementation", "implementation_at_write"):
        block = code[k]
        _require(isinstance(block, dict) and _is_sha256(block.get("sha256"))
                 and isinstance(block.get("files"), list) and block["files"], source,
                 f"code.{k} must carry a sha256 and a non-empty files list.")
    _require(isinstance(code["changed_during_run"], bool), source,
             "code.changed_during_run must be a boolean.")
    # Compared from the recorded implementation records themselves, not read from the flag: a
    # product whose flag says "unchanged" while its startup and at-write records differ is
    # refused, and so is one whose flag says "changed" while they agree. The refusal is
    # fail-closed at publication (and at every later read): the computation has already run;
    # what is refused is the product.
    start, at_write = code["implementation"], code["implementation_at_write"]
    if start["sha256"] != at_write["sha256"] or start["files"] != at_write["files"]:
        what = ("aggregate hashes differ" if start["sha256"] != at_write["sha256"]
                else "aggregate hashes agree but the per-file entries differ")
        raise SchemaError(
            f"{source}: implementation files changed while the stage ran (startup "
            f"{start['sha256'][:12]} vs at write {at_write['sha256'][:12]}: {what}); the product "
            f"does not describe one implementation and is refused.")
    _require(code["changed_during_run"] is False, source,
             "code.changed_during_run is set although the startup and at-write implementation "
             "records are identical; the code block contradicts itself and is refused.")
    _require(_is_sha256(manifest["checkpoint_sha256"]), source,
             f"checkpoint_sha256 {manifest['checkpoint_sha256']!r} is not a SHA-256 hex digest.")
    ident = manifest["run_identity"]
    _require(isinstance(ident, dict) and set(ident) == {"product_label", "invocation_id"}
             and all(isinstance(ident[k], str) and ident[k] for k in ident), source,
             "run_identity must carry exactly product_label and invocation_id (non-empty "
             "strings): the logical invocation every shard shares. The execution attempt (Slurm "
             "job id) belongs in the execution block, which is recorded but not compared.")
    _require(_valid_execution(manifest["execution"]), source,
             f"execution must carry exactly {list(EXECUTION_KEYS)} (job_id: a non-empty string, "
             f"or null outside Slurm); got {manifest['execution']!r}.")
    policy = manifest["seed_policy"]
    _require(isinstance(policy, dict) and "base_seed" in policy
             and (policy["base_seed"] is None or (isinstance(policy["base_seed"], int)
                                                  and not isinstance(policy["base_seed"], bool)))
             and isinstance(policy.get("per_rank"), str) and policy["per_rank"], source,
             "seed_policy must carry base_seed (int or null) and per_rank (string).")
    geom = manifest["window_geometry"]
    labels = manifest["condition_labels"]
    if stage == "experiment":
        _require(isinstance(geom, dict), source, "window_geometry is required for the experiment stage.")
        for k in ("n_frames", "step_frames"):
            _require(isinstance(geom.get(k), int) and not isinstance(geom[k], bool) and geom[k] > 0,
                     source, f"window_geometry.{k} {geom.get(k)!r} must be a positive integer.")
        _require(geom.get("span_frames") is None or (isinstance(geom["span_frames"], int)
                                                     and geom["span_frames"] > 0), source,
                 "window_geometry.span_frames must be a positive integer or null.")
        _require(isinstance(labels, list) and labels and all(isinstance(k, str) for k in labels)
                 and len(set(labels)) == len(labels), source,
                 "condition_labels must be a non-empty list of distinct strings for the "
                 "experiment stage.")
    else:
        _require(geom is None, source, "window_geometry must be null for the evaluation stage.")
        _require(labels is None, source, "condition_labels must be null for the evaluation stage.")
    stored = manifest["stored_optional_fields"]
    _require(isinstance(stored, list) and all(isinstance(k, str) for k in stored)
             and len(set(stored)) == len(stored)
             and all(k in OPTIONAL_FIELDS[stage] for k in stored), source,
             f"stored_optional_fields {stored!r} must list distinct optional fields of the {stage} "
             f"stage (allowed: {sorted(OPTIONAL_FIELDS[stage])}).")
    _require(list(manifest["observation_id_fields"]) == list(OBSERVATION_ID_FIELDS[stage]), source,
             f"observation_id_fields {manifest['observation_id_fields']} != "
             f"{list(OBSERVATION_ID_FIELDS[stage])}.")
    n_obs = manifest["n_observations"]
    _require(isinstance(n_obs, int) and not isinstance(n_obs, bool) and n_obs >= 0, source,
             f"n_observations {n_obs!r} must be a non-negative integer.")
    for k in ("rank", "world_size"):
        _require(manifest[k] is None or (isinstance(manifest[k], int)
                                         and not isinstance(manifest[k], bool)), source,
                 f"{k} must be an integer or null.")
    _require(isinstance(manifest["written_at"], str) and manifest["written_at"], source,
             "written_at must be a non-empty string.")
    if "shards" in manifest or "merged_from_shards" in manifest:
        shards, k = manifest.get("shards"), manifest.get("merged_from_shards")
        _require(isinstance(k, int) and not isinstance(k, bool) and k > 0
                 and isinstance(shards, list) and len(shards) == k, source,
                 "a merged manifest must carry merged_from_shards (a positive integer) and a "
                 "shards list of that length.")
        for i, rec in enumerate(shards):
            _require(isinstance(rec, dict) and set(rec) == set(SHARD_RECORD_KEYS)
                     and _valid_execution(rec["execution"])
                     and isinstance(rec["n_observations"], int)
                     and not isinstance(rec["n_observations"], bool)
                     and rec["n_observations"] >= 0, source,
                     f"shards[{i}] must record exactly {list(SHARD_RECORD_KEYS)} with a valid "
                     f"execution block and a non-negative observation count; got {rec!r}.")
        total = sum(rec["n_observations"] for rec in shards)
        _require(total == n_obs, source,
                 f"the shards' observation counts sum to {total}, not n_observations={n_obs}.")
    return manifest


def _is_integer_valued(arr) -> bool:
    a = np.asarray(arr)
    if a.dtype.kind in "iu":
        return True
    if a.dtype.kind == "b" or a.dtype.kind not in "f":
        return False
    return bool(np.all(np.isfinite(a)) and np.all(a == np.floor(a)))


def validate_product(arrays, *, stage, source="product", expect_n=None,
                     allow_empty: bool = False) -> dict:
    """Validate one product or shard against the full contract described in the module docstring.
    Returns the decoded manifest. Errors name the source, the field and the offending
    observation index.

    ``allow_empty`` admits a zero-observation SHARD (a rank that drew no work still writes a
    valid shard); a final stage product with no observations is refused regardless, since a
    report over nothing is not a result."""
    if stage not in STAGE_FIELDS:
        raise SchemaError(f"unknown stage {stage!r}")
    reject_obsolete(arrays, source=source)
    if MANIFEST_KEY not in arrays:
        raise SchemaError(f"{source}: no {MANIFEST_KEY}; not a schema-{ARTIFACT_SCHEMA_VERSION} "
                          f"product of the {stage} stage.")
    try:
        manifest = decode_manifest(arrays[MANIFEST_KEY])
    except (ValueError, TypeError) as exc:
        raise SchemaError(f"{source}: {MANIFEST_KEY} is not valid JSON ({exc}).")
    validate_manifest(manifest, stage=stage, source=source)
    fields = STAGE_FIELDS[stage]
    missing = [k for k in list(fields) + list(STAGE_RUN_FIELDS[stage]) if k not in arrays]
    if missing:
        raise SchemaError(f"{source}: required field(s) missing for the {stage} stage: {missing}.")
    n = int(np.asarray(arrays["map_estimate"]).shape[0])
    d = len(manifest["parameter_keys"])
    q = len(manifest["quantile_levels"])
    dims = {"N": n, "D": d, "Q": q, "S": int(manifest["n_summary_draws"])}
    for key, rule in fields.items():
        shape = tuple(np.asarray(arrays[key]).shape)
        want = tuple(dims[r] for r in rule)
        if shape != want:
            raise SchemaError(f"{source}: {key} has shape {shape}; expected {want} "
                              f"(N={n} observations, D={d} parameters, Q={q} levels).")
    declared = set(manifest["stored_optional_fields"])
    for key, rule in OPTIONAL_FIELDS[stage].items():
        if key in arrays and key not in declared:
            raise SchemaError(f"{source}: carries optional {key} but the manifest does not declare "
                              f"it in stored_optional_fields; optional storage is a run-level "
                              f"setting recorded in the contract.")
        if key in declared and key not in arrays:
            raise SchemaError(f"{source}: declares {key} in stored_optional_fields but the product "
                              f"lacks it.")
        if key in arrays:
            shape = tuple(np.asarray(arrays[key]).shape)
            want = tuple(dims[r] for r in rule)
            if shape != want:
                raise SchemaError(f"{source}: optional {key} has shape {shape}; expected {want} "
                                  f"(N={n}, S={dims['S']} summary draws, D={d}).")
            bad = ~np.isfinite(np.asarray(arrays[key], dtype=float))
            if bad.any():
                rows = np.unique(np.argwhere(bad)[:, 0])
                raise SchemaError(f"{source}: non-finite {key} for observation index(es) "
                                  f"{rows[:10].tolist()}{' ...' if rows.size > 10 else ''}.")
    if n == 0 and not allow_empty:
        raise SchemaError(f"{source}: no observations; a {stage} product over nothing is not a "
                          f"result (an empty shard is admitted only inside a merge).")
    if expect_n is not None and n != int(expect_n):
        raise SchemaError(f"{source}: {n} observations stored; {int(expect_n)} expected.")
    if int(manifest["n_observations"]) != n:
        raise SchemaError(f"{source}: manifest n_observations={manifest['n_observations']} "
                          f"but map_estimate holds {n} rows.")
    for key in _FINITE_FIELDS[stage]:
        bad = ~np.isfinite(np.asarray(arrays[key], dtype=float))
        if bad.any():
            rows = np.unique(np.argwhere(bad)[:, 0]) if bad.ndim > 1 else np.flatnonzero(bad)
            raise SchemaError(f"{source}: non-finite {key} for observation index(es) "
                              f"{rows[:10].tolist()}{' ...' if rows.size > 10 else ''} "
                              f"({stage} stage).")
    pq = np.asarray(arrays["posterior_quantiles"], dtype=float)
    if n and np.any(np.diff(pq, axis=-1) < 0):
        rows = np.unique(np.argwhere(np.diff(pq, axis=-1) < 0)[:, 0])
        raise SchemaError(f"{source}: posterior_quantiles decrease along the level axis for "
                          f"observation index(es) {rows[:10].tolist()}"
                          f"{' ...' if rows.size > 10 else ''}; quantiles must be nondecreasing.")
    for key in OBSERVATION_ID_FIELDS[stage]:
        if not _is_integer_valued(arrays[key]):
            raise SchemaError(f"{source}: {key} must be integer-valued (got dtype "
                              f"{np.asarray(arrays[key]).dtype}, non-integer entries).")
    if stage == "experiment":
        kinds = [str(k) for k in np.asarray(arrays["kinds"]).ravel()]
        if kinds != list(manifest["condition_labels"]):
            raise SchemaError(f"{source}: stored kinds {kinds} differ from the manifest's "
                              f"condition_labels {manifest['condition_labels']}.")
        ki = np.asarray(arrays["kind_index"]).astype(np.int64)
        if n and (ki.min() < 0 or ki.max() >= len(kinds)):
            raise SchemaError(f"{source}: kind_index out of range for {len(kinds)} condition "
                              f"label(s): min {int(ki.min())}, max {int(ki.max())}.")
    assert_unique_observations(observation_ids(arrays, stage), source=source)
    return manifest


def median_level_index(manifest: dict) -> int:
    """Index of the 0.50 level along the quantile axis, located from the manifest -- never assumed."""
    levels = [round(float(v), 12) for v in manifest["quantile_levels"]]
    return levels.index(0.50)


def assert_parameter_keys(manifest: dict, expected, *, source="product") -> None:
    """A consumer's parameter table must equal the product's, key for key and in order. Counting
    columns is not enough: two tables of equal length with a different row order would read every
    column as the wrong parameter."""
    got = [str(k) for k in manifest.get("parameter_keys", [])]
    want = [str(k) for k in expected]
    if got != want:
        raise SchemaError(f"{source}: parameter_keys {got} differ from this workflow's {want} "
                          f"(exact key and order match required).")


def observation_ids(arrays, stage) -> np.ndarray:
    """The ``(N, k)`` integer identifier tuples of a product's observations."""
    cols = [np.asarray(arrays[f]).astype(np.int64).ravel() for f in OBSERVATION_ID_FIELDS[stage]]
    return np.stack(cols, axis=1) if cols else np.empty((0, 0), np.int64)


def assert_unique_observations(ids: np.ndarray, *, source="product", expected=None) -> None:
    """No duplicate identifier tuple; and, when ``expected`` (an ``(M, k)`` array or a set of
    tuples) is given, the stored set must EQUAL it -- the right count with the wrong members is
    refused, and the message names what is missing and what is extra."""
    rows = [tuple(int(v) for v in r) for r in np.asarray(ids)]
    seen, dup = set(), set()
    for r in rows:
        (dup if r in seen else seen).add(r)
    if dup:
        raise SchemaError(f"{source}: duplicate observation identifier(s) "
                          f"{sorted(dup)[:10]}{' ...' if len(dup) > 10 else ''}.")
    if expected is not None:
        exp = {tuple(int(v) for v in r) for r in expected}
        missing, extra = sorted(exp - seen), sorted(seen - exp)
        if missing or extra:
            raise SchemaError(
                f"{source}: observation set differs from the expected inventory: "
                f"{len(missing)} missing {missing[:10]}{' ...' if len(missing) > 10 else ''}; "
                f"{len(extra)} unexpected {extra[:10]}{' ...' if len(extra) > 10 else ''}.")


def assert_compatible_manifests(manifests, *, sources=None) -> dict:
    """Shards of one computation must agree on every :data:`CONTRACT_KEYS` entry. Returns the
    shared contract (the first manifest's) or raises naming the first disagreeing key."""
    manifests = list(manifests)
    if not manifests:
        raise SchemaError("no manifests to compare.")
    sources = list(sources) if sources is not None else [f"shard {i}" for i in range(len(manifests))]
    ref = manifests[0]
    for m, src in zip(manifests[1:], sources[1:]):
        for key in CONTRACT_KEYS:
            if json.dumps(ref.get(key), sort_keys=True, default=_json_default) != \
               json.dumps(m.get(key), sort_keys=True, default=_json_default):
                raise SchemaError(
                    f"{src}: computation contract differs from {sources[0]} on {key!r}: "
                    f"{m.get(key)!r} != {ref.get(key)!r}. Shards of different computations "
                    f"are not merged.")
    return ref


def merged_manifest(contract: dict, *, n_observations: int, shard_manifests,
                    execution: dict) -> dict:
    """The manifest of a merged product: the shared contract, observation count updated, rank
    fields cleared, the merge step's OWN execution attempt recorded (``execution``, from
    :func:`execution_identity` at merge time), and the per-shard provenance that legitimately
    differs between shards -- rank, world size, observation count, write time and each shard's
    execution attempt (a replacement rank's own Slurm job, or none) -- retained under
    ``shards``."""
    shard_manifests = list(shard_manifests)
    out = dict(contract)
    out.update(n_observations=int(n_observations), rank=None, world_size=None,
               execution=dict(execution),
               merged_from_shards=len(shard_manifests),
               shards=[{"rank": m.get("rank"), "world_size": m.get("world_size"),
                        "n_observations": m.get("n_observations"),
                        "written_at": m.get("written_at"),
                        "execution": dict(m["execution"])} for m in shard_manifests],
               written_at=_now())
    return out


def load_product(path, *, stage, allow_empty: bool = False):
    """Read a product from disk, validate it, return ``(arrays, manifest)``. Arrays are copied out
    of the ``NpzFile`` so the handle closes here."""
    with np.load(str(path), allow_pickle=False) as d:
        arrays = {k: d[k] for k in d.files}
    manifest = validate_product(arrays, stage=stage, source=str(path), allow_empty=allow_empty)
    return arrays, manifest
